"""empty message

Revision ID: 38eff8a43dfa
Revises: e47ecb2e0e8a
Create Date: 2022-09-26 10:23:18.383851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38eff8a43dfa'
down_revision = 'e47ecb2e0e8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'page_id')
    )
    op.drop_table('tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('page_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], name='tags_page_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='tags_tag_id_fkey'),
    sa.PrimaryKeyConstraint('tag_id', 'page_id', name='tags_pkey')
    )
    op.drop_table('association')
    # ### end Alembic commands ###
