"""empty message

Revision ID: 502fbce7e863
Revises: ff559efa9b0e
Create Date: 2022-09-19 17:54:50.127638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502fbce7e863'
down_revision = 'ff559efa9b0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'age')
    # ### end Alembic commands ###
